### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by andyyuan78** [wbuntine/topic-models#1]
ubgpu@ubgpu:~/github/topic-models/HCA$ make
cd util; make 
make[1]: Entering directory `/home/ubgpu/github/topic-models/HCA/util'
cc -Wall  -I../util/ -I/home/wbuntine/include/ -O5 -DNDEBUG -ffast-math -DHAVE_INLINE -DH_THREADS  -c -o beta.o beta.c
beta.c:19:18: fatal error: srng.h: No such file or directory
 #include "srng.h"
                  ^
compilation terminated.
make[1]: *** [beta.o] Error 1
make[1]: Leaving directory`/home/ubgpu/github/topic-models/HCA/util'
make: **\* [util] Error 2
ubgpu@ubgpu:~/github/topic-models/HCA$ sudo make
cd util; make 
make[1]: Entering directory `/home/ubgpu/github/topic-models/HCA/util'
cc -Wall  -I../util/ -I/home/wbuntine/include/ -O5 -DNDEBUG -ffast-math -DHAVE_INLINE -DH_THREADS  -c -o beta.o beta.c
beta.c:19:18: fatal error: srng.h: No such file or directory
 #include "srng.h"
                  ^
compilation terminated.
make[1]: *** [beta.o] Error 1
make[1]: Leaving directory`/home/ubgpu/github/topic-models/HCA/util'
make: **\* [util] Error 2

**Comment by wbuntine** [comment]
To avoid this error, you can compile the packaged up version available from
mloss.org.  This has all the prereq libraries contained.

If you compile from the github version, you have to install "libstb" locally first.
      https://github.com/wbuntine/libstb
Install directions for it are in the top level README.  You will have to compile the library,
then place the *.h files and library somewhere on your system so HCA can find them.

Now go to the HCA directory and edit the Makefile.   Change the line:
              STB_HOME := /home/wbuntine
It should be that the library is in $(STB_HOME)/lib and the *.h files are in
$(STB_HOME)/include
